name: tests for backend

on:
    push:
        branches:
            - main
            - ci-test
        paths:
            - 'backend/**'

defaults:
    run:
        working-directory: backend/user-api

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                version: "0.8.19"
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: "pyproject.toml"
            
            - name: Install the project
              run: uv sync --locked --all-extras --dev

            - name: Run Linter and Formatting
              run: |
                uv run ruff check .
                uv run ruff format --check
            
            - name: Run MyPy Type Checking
              run:  uv run mypy .
            
            - name: Run tests
              run: uv run pytest
            
